---
# common
- hosts: tag_Group_web, tag_Group_lb
  become: yes
  gather_facts: no
  tasks:
  - name: install git
    apt: name=git state=installed

# web
- hosts: tag_Group_web
  become: yes
  roles:
  - role: web

- hosts: tag_Group_lb
  become: yes
  roles:
  - role: lb

