---
# ansible inventory setup
- hosts: localhost
  gather_facts: no

  tasks:

    - include_vars: ips.yml

    - include: hostnames.yml

# common
- hosts: web, lb
  become: yes
  gather_facts: no

  tasks:

  - name: install git
    apt: name=git state=installed

# web
- hosts: web
  become: yes
  roles:
  - role: web

- hosts: lb
  become: yes
  roles:
  - role: lb

